### PR TITLE
fix issue #8, #9

### PR DESCRIPTION
**Pull request by joodo**

### CODE REVIEW

**Review by aguilaair — APPROVED** [review]
Thanks!

**Comment by V3ntus** [comment]
Issue #8 is still present on Windows on the latest commit 933e79b73712932a87c1042f74a94d47ca28bc96

**Comment by aguilaair** [comment]
@V3ntus was it resolved?

**Comment by V3ntus** [comment]
> @V3ntus was it resolved?

It was a different issue due to my improper implementation of UpdatWindowManager where the onWindowClose callback Updat defines would be disposed because of my GoRouter setup. Resolved, thank you though!

**Pull request merged**
